.PHONY: check

check:
	mise exec -- stylua --check init.lua lua ftplugin
	nvim --headless +qa
	nvim --headless init.lua "+lua require('custom.check').run(function() assert(vim.wait(5000, function() return #vim.lsp.get_clients({ bufnr = 0, name = 'lua_ls' }) > 0 end), 'lua_ls did not attach'); assert(vim.fn.maparg('<C-t>', 'n') == '', '<C-t> must remain native'); assert(vim.fn.maparg('<leader>tf', 'n') ~= '', 'FTerm mapping is missing'); assert(vim.fn.maparg('<leader>x', 'n') == '', '<leader>x must remain a prefix'); assert(vim.fn.maparg('<leader>cx', 'n') ~= '', 'executable mapping is missing'); assert(vim.fn.maparg('<leader>th', 'n') ~= '', 'theme toggle mapping is missing') end)" +qa
	nvim --headless "+enew" "+setfiletype go" "+lua require('custom.check').run(function() assert(vim.wait(7000, function() return #vim.lsp.get_clients({ bufnr = 0, name = 'gopls' }) > 0 end), 'gopls did not attach'); local formatters = require('conform').list_formatters(0); assert(formatters[1].name == 'goimports' and formatters[2].name == 'gofumpt', 'unexpected Go formatter chain') end)" +qa
	nvim --headless "+Lazy load auto-dark-mode.nvim" "+Lazy load lualine.nvim" "+lua require('custom.check').run(function() vim.wait(300); require('auto-dark-mode').disable(); vim.wait(100); local theme = require('custom.theme'); theme.apply('light'); theme.toggle(); assert(vim.o.background == 'dark' and require('nvconfig').base46.theme == 'zenburn' and require('lualine').get_config().options.theme == 'iceberg_dark' and vim.api.nvim_get_hl(0, { name = 'NotifyBackground' }).bg == 0x3f3f3f, 'dark theme switch failed'); theme.toggle(); assert(vim.o.background == 'light' and require('nvconfig').base46.theme == 'flexoki-light' and require('lualine').get_config().options.theme == 'solarized_light' and vim.api.nvim_get_hl(0, { name = 'NotifyBackground' }).bg == 0xf2f0e5, 'light theme switch failed') end)" +qa
	nvim --headless "+Lazy load neoscroll.nvim" "+Lazy load nvim-ufo" "+Lazy load aerial.nvim" "+Lazy load nvim-lint" "+lua require('custom.check').run(function() local scroll = require('neoscroll.config').opts; assert(scroll.easing == 'sine' and scroll.duration_multiplier == 0.6 and scroll.easing_function == nil and scroll.performance_options == nil, 'invalid Neoscroll configuration'); local providers = require('ufo.config').provider_selector(0, 'python', ''); assert(providers[1] == 'treesitter' and providers[2] == 'indent', 'Python folding provider is disabled'); require('aerial').sync_load(); local aerial = require('aerial.config'); assert(aerial.layout.min_width == 24 and aerial.layout.max_width[1] == 48 and aerial.show_numbers == nil, 'invalid Aerial configuration'); for _, autocmd in ipairs(vim.api.nvim_get_autocmds({ group = 'lint' })) do assert(autocmd.event ~= 'InsertLeave' and autocmd.event ~= 'BufEnter', 'lint runs too frequently') end end)" +qa
	nvim --headless "+enew" "+lua vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'def outer():', '    if True:', '        return 1', '', 'outer()' }); vim.bo.filetype = 'python'" "+doautocmd BufReadPost" "+lua require('custom.check').run(function() vim.wo.foldlevel = 0; assert(vim.wait(2000, function() return vim.fn.foldlevel(1) > 0 end), 'Python folds were not produced'); assert(vim.fn.foldclosed(1) == 1, 'Python fold did not close') end)" +qa!
	nvim --headless "+Lazy load nvim-dap" "+lua require('custom.check').run(function() assert(vim.fn.executable('dlv') == 1, 'dlv is unavailable') end)" +qa
	git diff --check
