-- hardtime.nvim
--
-- 功能: 训练Vim正确使用方式，通过限制一些操作来培养更好的编辑习惯
--
-- 限制的操作:
-- 1. 重复按 h,j,k,l (使用数字前缀如 5j 代替)
-- 2. 重复按 <Left>, <Right>, <Up>, <Down> (使用更高效的移动命令)
-- 3. 重复按 <BS>, <Space> (使用更精确的删除和插入)
--
-- 推荐替代方式:
-- - 使用 w,b,e 进行单词级移动
-- - 使用 f,t,F,T 进行行内快速跳转
-- - 使用 gg,G 等进行文档级跳转
-- - 使用 /,? 进行搜索跳转
-- - 使用 数字+移动 如 5j 代替重复按键
--
-- 快捷键:
-- :HardTimeToggle - 开启/关闭 hardtime
-- :HardTimeStats - 显示使用统计信息
--
return {
  -- 改掉坏习惯，掌握Vim操作
  -- 'm4xshen/hardtime.nvim',
  -- lazy = false,
  -- dependencies = { 'MunifTanjim/nui.nvim' },
  -- opts = {},
}
